version: '3.9'

volumes:
  postgres_data:
  static_volume:
services:
  web:
    build: ./.
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/stocks_products/web/static
    expose:
      - 8000
#    ports:
#      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5555:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/stocks_products/web/static
    ports:
      - 80:80
    depends_on:
      - web